language: php

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
  # Allow failures until Travis build includes HHVM 3.20.2 which fix the issue with composer (see http://hhvm.com/blog/2017/06/07/hhvm-3-20.html)
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - travis_retry composer self-update

install:
  - travis_retry composer require --dev --no-update squizlabs/php_codesniffer
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text --exclude-group integration
