language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: hhvm
      dist: trusty

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --dev --no-update squizlabs/php_codesniffer
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text --exclude-group integration
